issuer: http://127.0.0.1:5556/dex

storage:
  type: sqlite3
  config:
    file: /tmp/dex.db

web:
  http: 0.0.0.0:5556
  allowedOrigins: ['*']

telemetry:
  http: 0.0.0.0:5558


staticClients:
  - id: webtech-frontend
    redirectURIs:
      - 'http://localhost:3000'
    name: 'Test webAPP'
    # secret: ZXhhbXBsZS1hcHAtc2VjcmV0
    public: true

connectors:
  - type: mockCallback
    id: mock
    name: Example

  - type: github
    # Required field for connector id.
    id: github
    # Required field for connector name.
    name: GitHub
    config:
      # Credentials can be string literals or pulled from the environment.
      clientID: 8d37b0cd7ee43f02bf46
      clientSecret: 301493596ce9dafe5db35b547336b7844d6de3bf
      redirectURI: http://127.0.0.1:5556/dex/callback


enablePasswordDB: true

staticPasswords:
  - email: "admin@example.com"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
